/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jocke' at '2017-07-18 14:02' with Gradle 3.1
 *
 * @author jocke, @date 2017-07-18 14:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
